version: '3.8'

services:
  apigateway:
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - servicio1
      - servicio2
    networks:
      - g2net

  servicio1:
    image: stackg2-servicio1:latest
    ports:
      - "5000:5000"
    networks:
      - g2net

  servicio2:
    image: stackg2-servicio2:latest
    ports:
      - "5001:5001"
    networks:
      - g2net

networks:
  g2net:
